#:import hex kivy.utils.get_color_from_hex

ThirdWindow:

<SplashArt>:
    name: "splash"
    canvas.before:
        Color:
            rgba: hex('#3241E4')
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        cols: 1
        padding: [(self.width - 160)/2, (self.height - 160)/2, 0, 0]
        Image
            source: './images/power-plug.png'
            allow_stretch: True
            size_hint: None, None
            size: 160, 160


        #Label: (maybe add the label, def add the fading effects after 3 seconds)
        #    text: "FatigueCheck"
        #    font_size: 30
        #    size_hint_y: None
        #    height: self.texture_size[1]
        #    on_press: app.root.current = "first"

<FirstWindow>:
    name: "first"
    canvas.before:
        Color:
            rgba: hex('#ECF2FE')
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        Label:
            font_name: "./fonts/static/Urbanist-Light.ttf"
            text: "Para qual tipo de cabo\ndeseja calcular dados?"
            pos_hint : {"x": 0, "top": 0}
            font_size: 24
            color: hex('#000000')
            
            #size: root.width/2, root.height/2
            #on_press: app.root.current = "splash"

        Button:
            font_name: "./fonts/static/Urbanist-ExtraLight.ttf"
            text: "Alumínio"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
        Button:
            font_name: "./fonts/static/Urbanist-ExtraLight.ttf"
            text: "ACSR"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}

<SecondWindow>:
    name: "second"
    canvas.before:
        Color:
            rgba: hex('#ECF2FE')
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 20, 20, 20, 20

        Label:
            text: "Insira os dados corretamente. As casas decimais devem ser separadas por um ponto. O diâmetro deve estar em milímetros e a força em Newtons"
            font_name: "./fonts/static/Urbanist-Light.ttf"
            font_size: 18
            color: hex('#000000')
            text_size: self.size
            halign: 'center'
            valign: 'middle'
        TextInput:
            id: layer_quantity
            multiline: False
            hint_text: "Número de cabos da camada de alumínio"    
            input_filter: "int"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
        TextInput:
            id: diameter
            multiline: False
            hint_text: "Diâmetro do fio de alumínio"    
            input_filter: "float"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
            #on_text: root.clear_text() if self.focus else None
        TextInput:
            id: force
            multiline: False
            hint_text: "Valor da força de tração"    
            input_filter: "float"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}

        Label: #insira quantos dados as tabelas irao pegar
            text: "Valores da amplitude vs ciclos"    
            font_name: "./fonts/static/Urbanist-Light.ttf"
            font_size: 18
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
            color: hex('#000000')
        TextInput:
            id: num_amplitude
            multiline: False
            hint_text: "Qunatidade de amplitudes"    
            input_filter: "int"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
        TextInput:
            id: num_ciclos
            multiline: False
            hint_text: "Qunatidade de ciclos"    
            input_filter: "int"
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}


        Label: #insira quantos dados as tabelas irao pegar
            text: "Valores da Tabela"    
            font_name: "./fonts/static/Urbanist-Light.ttf"
            font_size: 18
            size_hint: 0.75, 0.25
            pos_hint : {"center_x": .5}
            color: hex('#000000')

        ScrollView:
            #do_scroll_x=True
            GridLayout:
                cols: 5 #vai pegar input acima da tabela
                rows: 5 #vai pegar input acima da tabela
                spacing: 10

                size_hint_y: None
                row_default_height: 40
                height: self.minimum_height
                width: self.minimum_width

                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"              
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"    
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"              
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc"  
                TextInput:
                    id: amplitude1
                    hint_text: "amplitudeblablabla"   
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 
                TextInput:
                    id: N1
                    hint_text: "ciclos etcetc" 


<ThirdWindow>:
    name: "third"
    canvas.before:
        Color:
            rgba: hex('#3241E4')
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 20, 20, 20, 20

        Label:
            text: "Com base nos dados inseridos, temos que a vida útil do cabo é +++"
            font_name: "./fonts/static/Urbanist-Light.ttf"
            font_size: 24
            text_size: self.size
            halign: 'center'
            valign: 'middle'
        
        #moSTRAR DANO E VIDA
        
        Label:
            text: "E podemos assim traçar a curva S-N."
            font_name: "./fonts/static/Urbanist-Light.ttf"
            font_size: 24
            text_size: self.size
            halign: 'center'
            valign: 'middle'

        #show graph
        Image:
            source: "images/curvaSNExemplo.image"
            allow_stretch: True